// Re-export from split db modules for backward compatibility

export type { S2PaperInput } from './db/index';
export {
  addPaperToCollection,
  addTagToPaper,
  checkPapersInLibrary,
  closeDatabase,
  createCollection,
  createTag,
  deleteCollection,
  deletePaper,
  deleteTag,
  getCitationFetchTime,
  getCitationGraph,
  getCitationSubgraph,
  getCollectionByName,
  getCollections,
  getCollectionsForPaper,
  getPaperByArxivId,
  getPaperById,
  getPapers,
  getS2IdsByArxivIds,
  getTagByName,
  getTags,
  getTagsForPaper,
  initDatabase,
  insertPaper,
  isCitationNodeExpanded,
  removePaperFromCollection,
  removeTagFromPaper,
  saveCitationBatch,
  searchLibrary,
  toggleFavorite,
  updateCollection,
  updatePaperPdf,
  updateTag,
} from './db/index';
