// Re-export from split db modules for backward compatibility

export type {
  ChunkInsertData,
  EmbeddingStatusValue,
  IndexingStats,
  LibraryStats,
  SemanticSearchResult,
  VectorSearchResult,
} from './db/index';
export {
  addPaperToCollection,
  addTagToPaper,
  checkPapersInLibrary,
  closeDatabase,
  createCollection,
  createTag,
  deleteChunksForPaper,
  deleteCollection,
  deletePaper,
  deleteTag,
  getAllPaperPdfPaths,
  getCollectionByName,
  getCollections,
  getCollectionsForPaper,
  getCollectionsForPapers,
  getIndexingStats,
  getIndexingStatsFromDb,
  getLibraryStats,
  getPaperByArxivId,
  getPaperById,
  getPapers,
  getPapersNeedingEmbedding,
  getTagByName,
  getTags,
  getTagsForPaper,
  getTagsForPapers,
  getToolStats,
  getViewerState,
  hybridSearch,
  initDatabase,
  insertChunkWithEmbedding,
  insertPaper,
  logToolCall,
  removePaperFromCollection,
  removeTagFromPaper,
  saveViewerState,
  searchLibrary,
  setEmbeddingStatus,
  toggleFavorite,
  updateCollection,
  updatePaperMetadata,
  updatePaperPdf,
  updatePaperPdfPath,
  updateTag,
  vectorSearch,
} from './db/index';
